# Generated by Django 3.1 on 2020-12-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_accept_appotime_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question'),
        ),
        migrations.AlterField(
            model_name='appotime',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question'),
        ),
    ]
