# Generated by Django 3.1 on 2020-09-23 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=128)),
                ('administrator', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.base')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('tarclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.base')),
                ('person', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classmodel', models.ManyToManyField(to='blog.Classes')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contents', models.TextField()),
                ('tag', models.ManyToManyField(to='blog.Tags')),
                ('tarclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.classes')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DateField()),
                ('finish', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teachers')),
                ('task', models.ManyToManyField(to='blog.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.base')),
                ('person', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classmodel', models.ManyToManyField(to='blog.Classes')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ManyToManyField(to='blog.Teachers')),
                ('tarclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.classes')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ManyToManyField(to='blog.Students')),
                ('tarclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.classes')),
            ],
        ),
    ]
