# Generated by Django 2.2.5 on 2020-09-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsClasses',
            new_name='StudentClasses',
        ),
    ]
