# Generated by Django 3.1 on 2020-09-24 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200924_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteachers',
            name='person',
        ),
        migrations.RemoveField(
            model_name='classteachers',
            name='tarclass',
        ),
        migrations.RemoveField(
            model_name='studentclasses',
            name='classmodel',
        ),
        migrations.RemoveField(
            model_name='studentclasses',
            name='person',
        ),
        migrations.RemoveField(
            model_name='teacherclasses',
            name='classmodel',
        ),
        migrations.RemoveField(
            model_name='teacherclasses',
            name='person',
        ),
        migrations.RemoveField(
            model_name='students',
            name='base',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='base',
        ),
        migrations.AddField(
            model_name='base',
            name='students',
            field=models.ManyToManyField(to='blog.Students'),
        ),
        migrations.AddField(
            model_name='base',
            name='teachers',
            field=models.ManyToManyField(to='blog.Teachers'),
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(to='blog.Students'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teachers',
            field=models.ManyToManyField(to='blog.Teachers'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='auther',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.teachers'),
        ),
        migrations.RemoveField(
            model_name='students',
            name='person',
        ),
        migrations.AddField(
            model_name='students',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenttasks',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.students'),
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='person',
        ),
        migrations.AddField(
            model_name='teachers',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClassStudents',
        ),
        migrations.DeleteModel(
            name='ClassTeachers',
        ),
        migrations.DeleteModel(
            name='StudentClasses',
        ),
        migrations.DeleteModel(
            name='TeacherClasses',
        ),
    ]
