# Generated by Django 3.1 on 2020-09-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200925_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='auther',
        ),
        migrations.AddField(
            model_name='tasks',
            name='auther',
            field=models.ManyToManyField(to='blog.Teachers'),
        ),
    ]
