
# Generated by Django 3.1 on 2020-12-09 07:06



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201201_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttasks',
            name='isResult',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
