# Generated by Django 3.1 on 2020-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_base_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='students',
            field=models.ManyToManyField(blank=True, to='blog.Students'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(blank=True, to='blog.Students'),
        ),
    ]
