# Generated by Django 3.1 on 2020-09-29 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200930_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='make',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 8, 52, 45, 885246)),
        ),
    ]
