# Generated by Django 3.1 on 2020-09-29 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tasks_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='make',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 8, 56, 27, 109982)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tags'),
        ),
    ]
