# Generated by Django 3.1 on 2020-09-30 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200930_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='make',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 10, 25, 56, 418808)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='use_base',
            field=models.IntegerField(default=None),
        ),
    ]
