# Generated by Django 3.1 on 2020-09-30 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200930_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='use_base',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='make',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 10, 32, 37, 802384)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='use_base',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
