# Generated by Django 3.1 on 2020-09-30 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200930_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='use_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='make',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 10, 35, 25, 22448)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='use_base',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
