# Generated by Django 3.1 on 2020-09-30 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200930_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='make',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 8, 2, 56, 922663, tzinfo=utc)),
        ),
    ]
