# Generated by Django 3.1 on 2020-09-30 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200930_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='make',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
